### ISSUE TITLE
MICE not bolding main title

### ISSUE THREAD

**Issue by keithkade** [ecologylab/BigSemanticsJavaScript#26]
Example: http://ecologylab.net/research/bigsemantics/MICE/index.html?url=http://www.amazon.com/Discovery-Daft-Punk/dp/B000059MEK/ref=sr_1_1?s=music&ie=UTF8&qid=1365793732

**Comment by adunofaiur** [comment]
I can try and fix tomorrow

**Comment by adunofaiur** [comment]
For some reason the metadata_h1 class got removed from metadataRenderer.css. Should be fixed now.
