### ISSUE TITLE
title inherited when it shouldn't be in patent classification

### ISSUE THREAD

**Issue by andru1d** [ecologylab/BigSemanticsJavaScript#29]
extracting from

https://www.google.com/patents/US20140179312?dq=curation&hl=en&sa=X&ei=h20ZVbWwGIijgwTX6IFA&ved=0CDIQ6AEwAw

you can see in the attached imaged of MICE, each classification has the title of this page rather than its own title.

the initial title should be the anchor text of the link, which is the classification number.

![screen shot 2015-03-30 at 10 38 10 am](https://cloud.githubusercontent.com/assets/2532269/6899985/684357bc-d6c9-11e4-858f-d70138ff3624.png)

**Comment by keithkade** [comment]
It appears to be a wrapper issue not an extraction issue. I will fix

**Comment by keithkade** [comment]
Pushed wrapper fix so it now works with service. Will close issue once I've confirmed extraction extension gets it right as well.
