### ISSUE TITLE
generating bib takes forever and then fails for 1 acm proceedings article

### ISSUE THREAD

**Issue by andru1d** [ecologylab/BigSemanticsJavaScript#44]
test case:

https://ideamache.ecologylab.net/e/ngTbBIGEOd/

**Comment by keithkade** [comment]
For me it is failing quickly. Seems to be because the clipping's original metadata is wrong (just rich_document) and that is what is being used for generating the bib.

**Comment by andru1d** [comment]
i just created the clipping using the extraction and dragging into mache.
please use that as the test case.

thanks!

andruid

On Wed, Apr 13, 2016 at 1:31 PM, Kade Keith <notifications@github.com>
wrote:

> For me it is failing quickly. Seems to be because the clipping's original
> metadata is wrong (just rich_document) and that is what is being used for
> generating the bib.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ecologylab/BigSemanticsJavaScript/issues/44#issuecomment-209584457>
>



-- 
andruid kerne, ph.d.
director, interface ecology lab
associate professor, department of computer science and engineering
texas a&m university                   979.862.3684 fax
college station, tx 77843-3112       http://ecologylab.net

http://facebook.com/ecologylab

Interfaces are the multidimensional border zones through which the
interdependent relationships of people, activities, codes, components,
and systems are constituted. Interface ecology investigates the
dynamic interactions of media, cultures, and disciplines that
flow through interfaces.

**Comment by keithkade** [comment]
I can't recreate :/

![draganddrop](https://cloud.githubusercontent.com/assets/2426829/14505478/ed8b91a6-017e-11e6-8901-a77338411699.gif)

**Comment by andru1d** [comment]
try using that mache.

On Wed, Apr 13, 2016 at 1:52 PM, Kade Keith <notifications@github.com>
wrote:

> I can't recreate :/
>
> [image: draganddrop]
> <https://cloud.githubusercontent.com/assets/2426829/14505478/ed8b91a6-017e-11e6-8901-a77338411699.gif>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ecologylab/BigSemanticsJavaScript/issues/44#issuecomment-209593136>
>



-- 
andruid kerne, ph.d.
director, interface ecology lab
associate professor, department of computer science and engineering
texas a&m university                   979.862.3684 fax
college station, tx 77843-3112       http://ecologylab.net

http://facebook.com/ecologylab

Interfaces are the multidimensional border zones through which the
interdependent relationships of people, activities, codes, components,
and systems are constituted. Interface ecology investigates the
dynamic interactions of media, cultures, and disciplines that
flow through interfaces.

**Comment by keithkade** [comment]
Not fixed, but I've gotten closer. It seems to be a serialization/saving related. 

To recreate:

1. Start with empty mache. Select text on an acm page and drag in. 
2. That clipping will have the right md. And generating bib should work. (you can confirm by checking the value of `session.composition.elements[0].metadata.source.rawMetadata` in the console. 
3. Save and refresh the page. 
2. The clipping will no longer have the right md. Generating bib will not work. checking `session.composition.elements[0].metadata.source.rawMetadata` will just show rich_document

**Comment by keithkade** [comment]
Figured it out w/ nic's help. I'll push a fix tomorrow

**Comment by keithkade** [comment]
fixed https://github.com/ecologylab/IdeaMACHE/commit/f9a72feafb5a6c5d55f494b3b21ebc57b9a6d349
