### ISSUE TITLE
bibtex proceedings / journal still not getting generated for scholarly articles

### ISSUE THREAD

**Issue by andru1d** [ecologylab/BigSemanticsJavaScript#45]
https://ideamache.ecologylab.net/e/ngTbBIGEOd/

https://ideamache.ecologylab.net/e/QipzcEdz2n/

http://ideamache.ecologylab.net/v/4OKbNujAxi/

**Comment by keithkade** [comment]
this should have been fixed by https://github.com/ecologylab/BigSemanticsWrapperRepository/commit/1b4ab5d0762b09cf6e8011256242382192995612 , but the mmd from the service isn't up to date with what is in the repo.

@quyin  do I need to do anything else to get that change to be served?

**Comment by quyin** [comment]
It's supposed to be released automatically. I'll just take a look.

Kade Keith <notifications@github.com>于2016年5月2日 周一下午12:28写道：

> this should have been fixed by ecologylab/BigSemanticsWrapperRepository@
> 1b4ab5d
> <https://github.com/ecologylab/BigSemanticsWrapperRepository/commit/1b4ab5d0762b09cf6e8011256242382192995612>
> , but the mmd from the service isn't up to date with what is in the repo.
>
> @quyin <https://github.com/quyin> do I need to do anything else to get
> that change to be served?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ecologylab/BigSemanticsJavaScript/issues/45#issuecomment-216302685>
>
-- 
Best,
Yin Qu (屈垠）

**Comment by quyin** [comment]
@keithkade I found that submodules in the umbrella project (https://github.com/ecologylab/BigSemantics) haven't been updated for a while, and that's causing the service to be lagging behind the master branch. After updating the submodules and re-releasing, the service is up-to-date now. The problem @andru1d reported seems fixed now, but it'll be nice if you can double check that.

**Comment by keithkade** [comment]
thanks. after refreshing the md generate bib worked for me also
