### ISSUE TITLE
Implement getRepoSource() for BSService, BSExtension, BSAutoSwitch

### ISSUE THREAD

**Issue by quyin** [ecologylab/BigSemanticsJavaScript#49]
Used to get the repo source. Should return (through callback) an object containing spec on where the repo was loaded, in the same form as the 1st argument to RepoMan's constructor.

For BSService, repoSource should point to a web service URL.

For BSExtension, repoSource should point to whatever spec'ed by the extension, e.g. its Options page.

For BSAutoSwitch, repoSource is determined by the underlying implementation.

**Comment by quyin** [comment]
This should be used to solve the ontology visualizer / supported domain table issue.

**Comment by quyin** [comment]
The code for the extension is in https://github.com/ecologylab/ExtractionExtension

**Comment by teschty** [comment]
Alright, the API calls are completed, now I just need to use them in the ontology visualizer / supported domain table.

**Comment by quyin** [comment]
Cool!

Please test in both cases: with and without extension.

Let me know when you finish. I can release the MICE part. We'll need to ask @niclupfer to release the extension.

**Comment by teschty** [comment]
I tested it with and without the extension before commiting and it seems to be working well!

**Comment by teschty** [comment]
Okay, so OntoViz and the Supported Domains table now use the getRepoSource call to determine where to get mmdrepository.json. Tested with and without the extension (and switching the extension from api.ecologylab.net to localhost) and it appears to be working.

**Comment by andru1d** [comment]
Very cool.

Andruid

On Friday, May 27, 2016, Tyler Tesch <notifications@github.com> wrote:

> Okay, so OntoViz and the Supported Domains table now use the getRepoSource
> call to determine where to get mmdrepository.json. Tested with and without
> the extension (and switching the extension from api.ecologylab.net to
> localhost) and it appears to be working.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ecologylab/BigSemanticsJavaScript/issues/49#issuecomment-222259861>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACajrbsDb2Tb7xWRZ9-32wHuxNa9jGMGks5qF2V7gaJpZM4IoUyD>
> .
>


-- 
andruid kerne, ph.d.
director, interface ecology lab
associate professor, department of computer science and engineering
texas a&m university                   979.862.3684 fax
college station, tx 77843-3112       http://ecologylab.net

http://facebook.com/ecologylab

Interfaces are the multidimensional border zones through which the
interdependent relationships of people, activities, codes, components,
and systems are constituted. Interface ecology investigates the
dynamic interactions of media, cultures, and disciplines that
flow through interfaces.
